# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: .
    weight: 1
  - name: Help us
    url: donate
    weight: 10
  - name: Shipments
    url: shipments
    weight: 20
  - name: Fundraising events
    url: fundraising
    weight: 30
  - name: Social events
    url: events
    weight: 40  
  - name: Dancing group
    url: dancing
    weight: 45
  - name: Our team
    url: about
    weight: 50
  - name: Reports
    url: reports
    weight: 60
  - name: Funding
    url: funding
    weight: 70
  - name: Gallery
    url: gallery
    weight: 80
  # - name: Contact
  #   url: contact
  #   weight: 70
  # - name: Calendar
  #   url: calendar
  #   weight: 80
