[build]
  command = "npm install && hugo --gc --minify -b $URL && npm run index"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.165.0"
  GO_VERSION = "1.21.5"
  NODE_VERSION = "22"
  HUGO_ENABLEGITINFO = "false"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "npm install && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL && npm run index"

[context.branch-deploy]
  command = "npm install && hugo --gc --minify -b $DEPLOY_PRIME_URL && npm run index"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
